use super::MarkovChainModel;
use std::collections::HashSet;
pub struct StarNameGenerator {
    markov : MarkovChainModel,
    used_names : HashSet<String>
}

impl StarNameGenerator {
    pub const SOURCE_NAMES: &'static [&'static str] = &[
        "Alces",
        "Alcibades",
        "Acamar",
        "Alpha",
        "Arian",
        "Aghran",
        "Al-aqrab",
        "Al-Lat",
        "Allatu",
        "Alilat",
        "Ahir",
        "Andromeda",
        "An-nhar",
        //"Aquarius", // PRONE TO REPLICATE NEAR-WHOLESALE, MAYBE REMOVE
        "Auriga",
        "Auron",
        "Auton",
        //"Austrinus",
        "Akaiwa",
        "Artemesia",

        "Barrion",
        "Belhammond",
        "Berria",
        "Beta",
        "Brand",
        "Baal",
        "Ba'al",
        "Boron",
        "Bizen",

        // DISABLED CUZ GENERATOR MOSTLY JUST REPLICATES IT WHOLESALE
        //"Cassiopeia",
        "Cetus",
        "Caladan",
        "Canes",
        //"Canes Venatici",
        "Carina",
        
        // DISABLED CUZ GENERATOR MOSTLY JUST REPLICATES IT WHOLESALE
        // "Centaurus",
        "Cepheus",
        "Cernan",
        "Certus",
        "Coma",
        "Corascia",
        "Corusca",
        //"Coma Berenices",
        "Crax",
        "Crucis",
        "Cygnus",
        "Cygnon",
        "Chugoku",

        "Daedlus",
        "Delrune",
        "Dendra",
        "Dietmar",
        "Dithimar",
        "Dolens",
        "Doom",
        "Dragon",
        "Dresden",
        "Dromar",
        "Dryad",
        "Dyad",
        "Dsiban",

        "Ea",
        "Eidre",
        "Elisande",
        "Elrond",
        "Eradon",
        "Eriand",
        "Eridanus",
        "Eros",
        "Ersand",
        "Ezar",
        "Ezor",
        "Eridani",
        "Ebih",

        "Fallia",
        "Fand",
        "Feylan",
        "Fellian",
        "Font",
        "Fornax",
        "Fornath",
        "Foryx",
        "Fu",
        "Fune",
        "Furan",
        "Furiosa",
        "Furyx",

        "Ganon",
        "Gail",
        "Geisand",
        "Gemini",
        "Giausar",
        "Ginan",
        "Gloas",
        "Gomeisa",
        "Gond",
        "Guahayona",
        "Gudja",
        "Gumala",
        "Gydaron",
        "Gyron",

        "Hattusa",
        "Hassuna",
        "Hadar",
        "Haedis",
        "Hatysa",
        "Helion",
        "Helm",
        "Hexam",
        "Hydra",
        "Hylix",
        "Hund",
        "Hunor",

        "Iklil",
        "Indus",
        "Irena",
        "Iskand",
        "Itonda",
        "Izar",
        "Iota Leporis",
        "Ishtar",
        "Inanna",
        "Ilabrat",

        "Jabbah",
        "Jalar",
        "Jeyan",
        "Jerush",
        "Jishui",
        "Joshan",

        "Kaewkosin",
        "Kalausi",
        "Kamuy",
        "Karaka",
        "Keid",
        "Keran",
        "Khambalia",
        "Kitalpha",
        "Kolan",
        "Komndor",
        "Kornephoros",
        "Kuma",
        "Kurhah",
        "Kur",
        "Kurashiki",

        "Landrig",
        "Lantion",
        "Landuhar",
        "Larawag",
        "Lerna",
        "Lesath",
        "Lich",
        "Liscor",
        "Lonsan",
        "Lusan",
        "Lushar",
        "Lutris",
        "Lycilin",
        "Lyncis",

        "Maasaym",
        "Macondo",
        "Marfik",
        "Marsic",
        "Menkalinan",
        "Menkar",
        "Mensa",
        "Mirach",
        "Miram",
        "Mizar",
        "Monch",
        "Monoceros",
        "Moriah",
        "Mouhoun",
        "Mpingo",
        "Muscida",

        "Nahn",
        "Nalbus",
        "Naledi",
        "Nekkar",
        "Nembus",
        "Nenque",
        "Nihal",
        "Nimh",
        "Noquisi",
        "Norion",
        "Nosaxa",
        "Nox",
        "Nuki",
        "Nusakan",
        "Nushagak",
        "Nyamien",
        "Niushe",
        "Ninshubur",
        "Nergal",
        "Nippur",

        "Oan",
        "Ogma",
        "Okab",
        "Omoyo",
        "Ophiiochus",
        "Ophiuchi",
        "Orion",
        "Orkaria",
        "Oryx",
        "Okayama",

        "Parumleo",
        "Petra",
        "Peylus",
        "Pendayo",
        "Phact",
        "Phecda",
        "Pherkad",
        "Philhammon",
        "Phorion",
        "Phondar",
        "Pisces",
        "Pipirima",
        "Poerava",
        "Polaris",
        "Polis",
        "Pollux",
        "Prim",
        "Procyon",
        "Propus",
        "Proxam",

        "Ran",
        "Rasalas",
        "Rasalgethi",
        "Rastaban",
        "Regor",
        "Regulus",
        "Revati",
        "Rhaan",
        "Rigel",
        "Rohan",
        "Rotanev",
        "Ruchbah",
        "Rukbat",

        "Sabik",
        "Saclateni",
        "Sadachbia",
        "Sadalbari",
        "Sadr",
        "Saiph",
        "Samaya",
        "Sargas",
        "Sculptor",
        "Serpens",
        "Sextans",
        "Sham",
        "Sharjah",
        "Shaula",
        "Sheliak",
        "Sheratan",
        "Sika",
        "Sirius",
        "Situla",
        "Solaris",
        "Spica",
        "Stribor",
        "Styx",
        "Sualocin",
        "Subra",
        "Suhail",
        "Sulafat",
        "Syrma",
        "Shaowei",

        "Tabit",
        "Taika",
        "Taiyangshou",
        "Taiyi",
        "Tangra",
        "Tarazad",
        "Tenthan",
        "Terebellum",
        "Tevel",
        "Thabit",
        "Theemin",
        "Thuban",
        "Tiaki",
        "Tianguan",
        "Tianyi",
        "Timir",
        "Tojil",
        "Toliman",
        "Tonatiuh",
        "Trantor",
        "Trinus",
        "Tsang",
        "Tsin",
        "Tucana",
        "Tuiren",
        "Tureis",
        
        "Uabb",
        "Uhlan",
        "Uht",
        "Ukdah",
        "Ukhab",
        "Uklun",
        "Ull",
        "Umman",
        "Unukalhai",
        "Unurgunite",
        "Ur",
        "Uruk",
        "Uten",
        "Uuba",
        "Ube",

        "Vega",
        "Veylan",
        "Vindemiatrix",
        "Viss",
        "Virgo",
        "Voss",
        "Vox",

        "Waiping",
        "Wasat",
        "Walhannis",
        "Weynhab",
        "Wezen",
        "Windarr",
        "Wolcan",
        "Wulrant",
        "Wouri",
        "Wurren",
        "Weyr",
        "Wir",

        "Xamidimura",
        "Xerant",
        "Xeyhab",
        "Xihe",
        "Xo",
        "Xoss",
        "Xuange",

        "Yang",
        "Yanda",
        "Yantris",
        "Yed",
        "Yehalan",
        "Yildun",
        "Yixam",
        "Yondarr",
        "Yoss",
        "Yorian",
        "Yoht",

        "Zaniah",
        "Zass",
        "Zaurak",
        "Zhang",
        "Zibal",
        "Zin",
        "Zoss",
        "Zoloss",
        "Zosma",
        "Zuben",
        "Zynath",
    ];

    pub fn new() -> Self {
        let mut markov = MarkovChainModel::new(3);
        let mut used_names : HashSet<String> = HashSet::new();
        let mut names = Vec::<String>::new();
        for starname in Self::SOURCE_NAMES {
            names.push(starname.to_string());
            used_names.insert(starname.to_string());
        }
        markov.build(&names, 0.00001);

        Self {
            markov,
            used_names
        }
    }

    pub fn next(&mut self) -> String {
        let mut res : String = self.markov.generate();

        while res.len() > 15 || self.used_names.contains(&res) {
            res = self.markov.generate();
        }
        self.used_names.insert(res.clone());

        res
    }
}